// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPreviewFilter(filterName: string): $CancellablePromise<string> {
    return $Call.ByID(1044038231, filterName);
}

export function ClearRecentProjects(): $CancellablePromise<void> {
    return $Call.ByID(1433503035);
}

export function CreateDocument(name: string, width: number, height: number, unit: string, physicalWidth: number, physicalHeight: number, resolutionDPI: number, background: string): $CancellablePromise<$models.DocumentSpec> {
    return $Call.ByID(317347380, name, width, height, unit, physicalWidth, physicalHeight, resolutionDPI, background);
}

export function FinalizeAxiaProjectOpen(sessionID: string, accepted: boolean): $CancellablePromise<void> {
    return $Call.ByID(52235181, sessionID, accepted);
}

export function GetEditorStatus(): $CancellablePromise<$models.EditorStatus> {
    return $Call.ByID(3826648460);
}

/**
 * ImportDroppedFiles reads the files a user dragged onto the window (native
 * OS drag-and-drop, delivered as absolute paths by the Wails runtime). Unlike
 * SelectImageFiles, a dropped file may be a folder or an unsupported format,
 * so invalid entries are skipped and reported instead of aborting the whole
 * drop.
 */
export function ImportDroppedFiles(paths: string[] | null): $CancellablePromise<$models.DroppedFilesResult> {
    return $Call.ByID(3752842461, paths);
}

export function ListRecentProjects(): $CancellablePromise<$models.RecentProject[] | null> {
    return $Call.ByID(4290737504);
}

export function OpenAxiaProject(): $CancellablePromise<$models.OpenedAxiaProject> {
    return $Call.ByID(1342011991);
}

export function OpenRecentProject(path: string): $CancellablePromise<$models.OpenedAxiaProject> {
    return $Call.ByID(1491084571, path);
}

export function PrepareAxiaProjectSave(suggestedName: string, currentPath: string, saveAs: boolean): $CancellablePromise<$models.ProjectSaveTarget> {
    return $Call.ByID(2430081129, suggestedName, currentPath, saveAs);
}

export function PrepareExportedImage(suggestedName: string, mimeType: string): $CancellablePromise<$models.ExportSaveTarget> {
    return $Call.ByID(3956774504, suggestedName, mimeType);
}

export function PrepareRecentThumbnail(path: string): $CancellablePromise<string> {
    return $Call.ByID(812954229, path);
}

export function RecordRecentProject(path: string, name: string, width: number, height: number): $CancellablePromise<$models.RecentProject> {
    return $Call.ByID(553526892, path, name, width, height);
}

export function ReleaseAxiaProjectAssets(): $CancellablePromise<void> {
    return $Call.ByID(2208318215);
}

export function ReleaseImageImports(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2282562931, ids);
}

export function ReleasePDFImport(id: string): $CancellablePromise<void> {
    return $Call.ByID(74252529, id);
}

export function RemoveRecentProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(4051839103, path);
}

export function SaveExportedImage(suggestedName: string, dataURL: string, mimeType: string): $CancellablePromise<string> {
    return $Call.ByID(3781007788, suggestedName, dataURL, mimeType);
}

export function SaveExportedPNG(suggestedName: string, dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(1175754146, suggestedName, dataURL);
}

export function SelectImageFile(): $CancellablePromise<$models.ImportedImage> {
    return $Call.ByID(4262026332);
}

export function SelectImageFiles(): $CancellablePromise<$models.ImportedImage[] | null> {
    return $Call.ByID(398204413);
}

export function SelectPDFFile(): $CancellablePromise<$models.PDFImportSource> {
    return $Call.ByID(119417331);
}

export function SetDocumentDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(2373944190, dirty);
}
