// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DocumentSpec {
    "id": string;
    "name": string;
    "width": number;
    "height": number;
    "unit": string;
    "physicalWidth": number;
    "physicalHeight": number;
    "resolutionDpi": number;
    "colorSpace": string;
    "background": string;
    "createdAt": string;
}

/**
 * DroppedFilesResult is the outcome of importing a native OS drag-and-drop.
 */
export interface DroppedFilesResult {
    "images": ImportedImage[] | null;
    "errors": string[] | null;
}

export interface EditorStatus {
    "appName": string;
    "engine": string;
    "documentOpen": boolean;
}

export interface ExportSaveTarget {
    "token": string;
    "path": string;
}

export interface ImportedImage {
    "id": string;
    "name": string;
    "width": number;
    "height": number;
    "mimeType": string;
    "sourceUrl": string;
    "byteSize"?: number;
    "resolutionDpiX"?: number;
    "resolutionDpiY"?: number;
    "resolutionSource"?: string;
}

export interface OpenedAxiaProject {
    "path": string;
    "manifest": string;
    "assetUrls": { [_ in string]?: string } | null;
    "sessionId": string;
}

export interface ProjectSaveTarget {
    "token": string;
    "path": string;
}

export interface RecentProject {
    "id": string;
    "path": string;
    "name": string;
    "width": number;
    "height": number;
    "modifiedAt": string;
    "lastOpenedAt": string;
    "thumbnailUrl": string;
    "thumbnailVersion": number;
    "available": boolean;
}
