// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPreviewFilter(arg1) {
  return window['go']['main']['App']['ApplyPreviewFilter'](arg1);
}

export function CreateDocument(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateDocument'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetEditorStatus() {
  return window['go']['main']['App']['GetEditorStatus']();
}

export function SelectImageFiles() {
  return window['go']['main']['App']['SelectImageFiles']();
}
