// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyPreviewFilter(arg1:string):Promise<string>;

export function CreateDocument(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number,arg7:number,arg8:string):Promise<main.DocumentSpec>;

export function GetEditorStatus():Promise<main.EditorStatus>;

export function SelectImageFiles():Promise<Array<main.ImportedImage>>;
